# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('starter', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('full_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'comics')),
                ('panel1', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'comics')),
                ('panel2', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'comics')),
                ('panel3', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'comics')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='artists.Artist')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comics.Comic')),
                ('portal_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='comics.Comic')),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True, max_length=250)),
                ('code', models.CharField(blank=True, help_text=b'Upload link is http://corpsey.trubble.club/contribute/upload/CODE_HERE/', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('panel1', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'contributions')),
                ('panel2', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'contributions')),
                ('panel3', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'contributions')),
                ('pending', models.BooleanField(default=True)),
                ('has_panels', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='comics.Comic')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=b'comics')),
                ('portal_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uturn', to='comics.Comic')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comics.Contribution')),
                ('rule_broke', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_broke', to='comics.Rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
